-- Export MySQL — Patrimoine mondial UNESCO (jeu issu de OpenRefine / CSV)
-- Source : unesco_na.csv (champs alignés sur le corpus exporté)
-- Encodage : UTF-8 (utf8mb4)
--
-- Import :
--   mysql -u root -p < corpus_unesco.sql

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP DATABASE IF EXISTS `corpus_ctm`;
CREATE DATABASE `corpus_ctm` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `corpus_ctm`;

CREATE TABLE `sites_unesco` (
  `id` int unsigned NOT NULL COMMENT 'Identifiant UNESCO',
  `nom` varchar(512) NOT NULL,
  `image` varchar(1024) DEFAULT NULL,
  `description` text NOT NULL,
  `date_inscription` date DEFAULT NULL COMMENT 'Date d''inscription (liste indicative / bien inscrit)',
  `geo` varchar(128) DEFAULT NULL COMMENT 'Coordonnées lat,lon',
  `categorie` varchar(32) DEFAULT NULL COMMENT 'Cultural, Natural, Mixed',
  `pays` varchar(128) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_pays` (`pays`),
  KEY `idx_cat` (`categorie`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `sites_unesco` (`id`, `nom`, `image`, `description`, `date_inscription`, `geo`, `categorie`, `pays`) VALUES
(8,'Ichkeul National Park','https://commons.wikimedia.org/wiki/Special:FilePath/(لحظة_غروب_الشمس_ـ_محمية_إشكل_(تونس.jpg','Le lac et les zones humides de l''Ichkeul constituent un relais indispensable pour des centaines de milliers d''oiseaux migrateurs – canards, oies, cigognes, flamants roses, etc. – qui viennent s''y nourrir et y nicher. Le lac est l''ultime vestige d''une chaîne de lacs qui s''étendait jadis à travers l''Afrique du Nord.','1980-01-01','37.123444,9.655444','Natural','Tunisie'),
(36,'Medina of Tunis','https://commons.wikimedia.org/wiki/Special:FilePath/Terrasses_de_la_médina_de_Tunis.jpg','Sous le règne des Almohades et des Hafsides, du XII e au XVI e siècle, Tunis a été considérée comme l''une des villes les plus importantes et les plus riches du monde islamique. Quelque 700 monuments dont des palais, des mosquées, des mausolées, des medersa et des fontaines témoignent de ce remarquable passé.','1979-01-01','36.7990274,10.1700595','Cultural','Tunisie'),
(37,'archaeological site of Carthage','https://commons.wikimedia.org/wiki/Special:FilePath/Archaeological_Site_of_Carthage-130237.jpg','Fondée dès le IX e siècle av. J.-C. sur le golfe de Tunis, Carthage établit à partir du VI e siècle un empire commercial s''étendant à une grande partie du monde méditerranéen et fut le siège d''une brillante civilisation. Au cours des longues guerres puniques, elle occupa des territoires de Rome, mais celle-ci la détruisit finalement en 146 av. J.-C. Une seconde Carthage, romaine celle-là, fut alors fondée sur ses ruines.','1979-01-01','36.85788,10.33084','Cultural','Tunisie'),
(38,'Roman amphitheatre of El Jem','https://commons.wikimedia.org/wiki/Special:FilePath/Amphi_El_Jem.jpg','Dans la petite bourgade d''El Jem s''élèvent les ruines impressionnantes du plus grand colisée d''Afrique du Nord, immense amphithéâtre où pouvaient prendre place 35 000 spectateurs. Cette construction du III e siècle illustre l''extension et la grandeur de l''Empire romain.','1979-01-01','35.29638889,10.70694444','Cultural','Tunisie'),
(102,'Qal''at Bani Hammad','https://commons.wikimedia.org/wiki/Special:FilePath/28-2_Kalâa_de_Beni_Hammad_(3).jpg','Dans un site montagneux d’une saisissante beauté, les ruines de la première capitale des émirs hammadides, fondée en 1007 et démantelée en 1152, nous restituent l’image authentique d’une ville musulmane fortifiée. Sa mosquée, avec sa salle de prière de 13 nefs à 8 travées, est l’une des plus grandes d’Algérie.','1980-01-01','35.813888888889,4.7933333333333','Cultural','Algérie'),
(170,'Medina of Fez','https://commons.wikimedia.org/wiki/Special:FilePath/Medina_of_Fes,_Marocco.jpg','Fondée au IXe siècle, Fès a connu sa période faste aux XIIIe et XIVe siècles, sous la dynastie mérinide, quand elle supplanta Marrakech comme capitale du royaume. Le tissu urbain et les monuments essentiels de la médina remontent à cette période : médersa, fondouks, palais et demeures, mosquées, fontaines, etc. En dépit du transfert du siège de la capitale à Rabat, en 1912, elle garde son statut de capitale culturelle et spirituelle du pays.','1981-01-01','34.0625,-4.9725','Cultural','Maroc'),
(179,'Tassili n''Ajjer','https://commons.wikimedia.org/wiki/Special:FilePath/Tassili_Desert_Algeria.jpg','Cet étrange paysage lunaire de grand intérêt géologique abrite l’un des plus importants ensembles d’art rupestre préhistorique du monde. Plus de 15 000 dessins et gravures permettent d’y suivre, depuis 6000 av. J.-C. jusqu’aux premiers siècles de notre ère, les changements du climat, les migrations de la faune et l’évolution de la vie humaine aux confins du Sahara. Le panorama de formations géologiques présente un intérêt exceptionnel avec ses « forêts de rochers » de grès érodé.','1982-01-01','25.666666666667,9','Mixed','Algérie'),
(184,'Archaeological Site of Sabratha','https://commons.wikimedia.org/wiki/Special:FilePath/Theatre_of_Sabratha,_Libya.jpg','Comptoir phénicien drainant les produits de l''Afrique intérieure, Sabratha fit partie de l''éphémère royaume numide de Massinissa avant d''être romanisée et reconstruite aux II e et III e siècles.','1982-01-01','32.80528,12.485','Cultural','Libye'),
(188,'M''zab','https://commons.wikimedia.org/wiki/Special:FilePath/Ksar_Beni_Isguen_2.jpg','Le paysage de la vallée du M’Zab, créé au Xe siècle par les Ibadites autour de leurs cinq ksour , ou villages fortifiés, semble être resté intact. Simple, fonctionnelle et parfaitement adaptée à l’environnement, l’architecture du M’Zab a été conçue pour la vie en communauté, tout en respectant les structures familiales. C’est une source d’inspiration pour les urbanistes d’aujourd’hui.','1982-01-01','32.487222222222,3.6813888888889','Cultural','Algérie'),
(191,'Djemila','https://commons.wikimedia.org/wiki/Special:FilePath/Roman_Ruins_of_Djemila_in_Sétif,_Algeria.jpg','Djémila, ou Cuicul, avec son forum, ses temples et ses basiliques, ses arcs de triomphe et ses maisons, à 900 m d’altitude, est un exemple remarquable d’urbanisme romain adapté à un site montagneux.','1982-01-01','36.32056,5.73667','Cultural','Algérie'),
(193,'Tipaza','https://commons.wikimedia.org/wiki/Special:FilePath/Mzafran_مزفران_-_panoramio.jpg','Sur les rives de la Méditerranée, Tipasa, ancien comptoir punique, fut occupé par Rome, qui en fit une base stratégique pour la conquête des royaumes mauritaniens. Il comprend un ensemble unique de vestiges phéniciens, romains, paléochrétiens et byzantins, voisinant avec des monuments autochtones, tel le Kbor er Roumia, grand mausolée royal de Maurétanie.','1982-01-01','36.594180555556,2.4430222222222','Cultural','Algérie'),
(194,'Timgad','https://commons.wikimedia.org/wiki/Special:FilePath/Timgad_Ruins_Panorama.jpg','Sur le versant nord des Aurès, Timgad fut créée ex nihilo , en 100 apr. J.-C., par l’empereur Trajan comme colonie militaire. Avec son enceinte carrée et son plan orthogonal commandé par le cardo et le decumanus , les deux voies perpendiculaires qui traversaient la ville, c’est un exemple parfait d’urbanisme romain.','1982-01-01','35.484237,6.468666','Cultural','Algérie'),
(331,'Medina of Marrakesh','https://commons.wikimedia.org/wiki/Special:FilePath/Menara_Garden,Morocco,Marrakech.jpg','Fondée en 1070-1072 par les Almoravides (1056-1147), Marrakech fut longtemps un centre politique, économique et culturel majeur de l''Occident musulman, régnant sur l''Afrique du Nord et l''Andalousie. Des monuments grandioses remontent à cette période : la mosquée de la Koutoubiya, la Casbah, les remparts, les portes monumentales, les jardins, etc. Plus tard, la ville accueillera d''autres merveilles, tels le palais Bandiâ, la medersa Ben Youssef, les tombeaux saâdiens, de grandes demeures, etc. La place Jamaâ El Fna, véritable théâtre en plein air, émerveille toujours les visiteurs.','1985-01-01','31.63139,-7.98667','Cultural','Maroc'),
(332,'Punic Town of Kerkuane and its Necropolis','https://commons.wikimedia.org/wiki/Special:FilePath/Punic_Town_of_Kerkuane_and_its_Necropolis-130314.jpg','Cette cité phénicienne, sans doute abandonnée pendant la première guerre punique (vers 250 av. J.-C.), et n''ayant de ce fait pas été reconstruite par les Romains, nous offre les seuls vestiges d''une ville phénico-punique qui ait subsisté. Ses maisons ont été construites selon un plan type, suivant un modèle d''urbanisme très élaboré.','1985-01-01','36.9464,11.0992','Cultural','Tunisie'),
(362,'Old Town of Ghadamès','https://commons.wikimedia.org/wiki/Special:FilePath/Ghadames_Old_city_from_the_air_other_side.jpg','Bâtie dans une oasis, Ghadamès, « la perle du désert », est une des plus anciennes cités présahariennes et un exemple exceptionnel d''habitat traditionnel. Son architecture domestique se caractérise par les différentes fonctions assignées à chaque niveau : rez-de-chaussée servant de réserve à provisions, étage familial surplombant des passages couverts aveugles qui permettent une circulation presque souterraine dans la ville et terrasses à ciel ouvert réservées aux femmes.','1986-01-01','30.132,9.497','Cultural','Libye'),
(444,'Aït Benhaddou','https://commons.wikimedia.org/wiki/Special:FilePath/Ksar_Aït_Benhaddou,_Marocco_(أيت_بن_حدو،_المغرب,_ⴰⵢⵜ_ⵃⴰⴷⴷⵓ).jpg','Ensemble de bâtiments de terre entourés de murailles, le ksar est un type d''habitat traditionnel présaharien. Les maisons se regroupent à l''intérieur de ses murs défensifs renforcés par des tours d''angle. Aït-Ben-Haddou, situé dans la province de Ouarzazate, est un exemple frappant de l''architecture du Sud marocain.','1987-01-01','31.05,-7.1333333333333','Cultural','Maroc'),
(498,'Medina of Sousse','https://commons.wikimedia.org/wiki/Special:FilePath/Sousse_Kasbah.JPG','Sousse, important port commercial et militaire sous les Aghlabides (800-909), est un exemple typique de ville des premiers siècles de l''islam. Avec sa casbah, ses remparts, sa médina et sa Grande Mosquée, la mosquée Bu Ftata et son ribat typique, à la fois fort et édifice religieux, elle était l''un des éléments d''un système de défense de la côte.','1988-01-01','35.8278,10.6386','Cultural','Tunisie'),
(499,'Kairouan','https://commons.wikimedia.org/wiki/Special:FilePath/View_of_Kairouan_from_the_Minaret_of_the_Great_Mosque_-_Tunisia_-_1899.jpg','Fondée en 670, la ville de Kairouan a prospéré sous la dynastie aghlabide, au IX e siècle. Malgré le transfert de la capitale politique à Tunis au XII e siècle, Kairouan est restée la première ville sainte du Maghreb. Son riche patrimoine architectural comprend notamment la Grande Mosquée, avec ses colonnes de marbre et de porphyre, et la mosquée des Trois-Portes qui date du IX e siècle.','1988-01-01','35.68333333333333,10.1','Cultural','Tunisie'),
(506,'Banc d''Arguin National Park','https://commons.wikimedia.org/wiki/Special:FilePath/PNBA_43.JPG','Situé le long de la côte atlantique, ce parc est formé de dunes de sable, de zones côtières marécageuses, de petites îles et d''eaux littorales peu profondes. L''austérité du désert et la richesse biologique de la zone marine créent un paysage terrestre et marin exceptionnellement contrasté. Une remarquable diversité d''oiseaux migrateurs y passent l''hiver. On y trouve également plusieurs espèces de tortues marines ainsi que des dauphins, que les pêcheurs utilisent pour rabattre les bancs de poissons.','1989-01-01','20.234722,-16.108889','Natural','Mauritanie'),
(565,'Casbah of Algiers','https://commons.wikimedia.org/wiki/Special:FilePath/Fonds_André_Raymond_(1925-2011)_-_Algérie_-_Alger_-_Vue_surplombante_sur_les_toits_de_la_ville_(MédiHAL_4106832).jpg','Dans l’un des plus beaux sites maritimes de la Méditerranée, surplombant les îlots où un comptoir carthaginois fut installé dès le IVe siècle av. J.-C., la Casbah constitue un type unique de médina , ou ville islamique. Lieu de mémoire autant que d’histoire, elle comprend des vestiges de la citadelle, des mosquées anciennes, des palais ottomans, ainsi qu’une structure urbaine traditionnelle associée à un grand sens de la communauté.','1992-01-01','36.78333,3.06028','Cultural','Algérie'),
(794,'Dougga','https://commons.wikimedia.org/wiki/Special:FilePath/Dougga,_Beja.jpg','Avant l''annexion romaine de la Numidie, la ville de Thugga, construite sur une colline surplombant une plaine fertile, a été la capitale d''un État libyco-punique. Elle a prospéré sous la domination romaine et byzantine mais a décliné au cours de la période islamique. Les ruines visibles aujourd''hui témoignent de manière imposante des ressources d''une petite ville romaine aux frontières de l''Empire.','1997-01-01','36.42333333,9.22027778','Cultural','Tunisie'),
(836,'Volubilis','https://commons.wikimedia.org/wiki/Special:FilePath/Volubilis,Morocco.jpg','La capitale de la Maurétanie, fondée au III e siècle av. J.-C., fut un avant-poste important de l''Empire romain et a été ornée de nombreux beaux monuments. Il en subsiste d''importants vestiges dans le site archéologique, situé dans une région agricole fertile. La ville devait devenir plus tard, pendant une brève période, la capitale d''Idriss I e r , fondateur de la dynastie des Idrissides, enterré non loin de là, à Moulay Idriss.','1997-01-01','34.071111111111,-5.5536111111111','Cultural','Maroc'),
(1058,'Medina of El Jadida','https://commons.wikimedia.org/wiki/Special:FilePath/Mazagan_(El_Jadida).jpg','Les fortifications portugaises de Mazagan, qui font aujourd’hui partie de la ville d’El Jadida, à 90 km au sud-ouest de Casablanca, furent édifiées comme colonie fortifiée sur la côte atlantique au début du XVI e siècle. La colonie fut reprise par les Marocains en 1769. Les fortifications, avec leurs bastions et remparts, constituent un exemple précoce de l’architecture militaire de la Renaissance. Les édifices portugais encore visibles sont la citerne et l’église de l’Assomption, construite dans le style manuélin (gothique tardif). La ville portugaise de Mazagan, l’un des premiers établissements en Afrique occidentale des explorateurs portugais qui faisaient route vers l’Inde, offre un témoignage exceptionnel des influences croisées entre les cultures européenne et marocaine, qui apparaissent clairement dans l’architecture, la technologie et l’urbanisme.','2004-01-01','33.259972,-8.509576','Cultural','Maroc');

SET FOREIGN_KEY_CHECKS = 1;
